### ISSUE TITLE
GitHub API Failure

### ISSUE THREAD

**Issue by haneefmubarak** [LogIN-/ospnc#10]
Apparently there's something wrong with the GH API being used. This is where a search for 'sock' takes you:

[`https://api.github.com/search/repositories%3Fq%3Dsock%26sort%3Dstars%26order%3Ddesc`](https://api.github.com/search/repositories%3Fq%3Dsock%26sort%3Dstars%26order%3Ddesc):

```
{
  "message": "Not Found",
  "documentation_url": "https://developer.github.com/v3"
}
```

**Comment by LogIN-** [comment]
Thanks,
it looks that this urlencoding in link is bad since is you do this:
