### ISSUE TITLE
Cross-Origin issue

### ISSUE THREAD

**Issue by pomeh** [LogIN-/ospnc#11]
On Windows, when I open http://ivantomic.com/projects/ospnc/ in Google Chrome 40 (latest stable at the moment), in private mode with no extensions enabled, I got this in the console:

     GET http://ivantomic.com:8089/socket.io/?EIO=2&transport=polling&t=1423839586611-11
    XMLHttpRequest cannot load http://ivantomic.com:8089/socket.io/?EIO=2&transport=polling&t=1423839586611-11. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://ivantomic.com' is therefore not allowed access. The response had HTTP status code 503.

I got the same result using Firefox 30.

**Comment by LogIN-** [comment]
It seems like socket.io issue, I'll see what I can do. Thanks!
