### ISSUE TITLE
Website down?

### ISSUE THREAD

**Issue by ljharb** [LogIN-/ospnc#21]
http://ivantomic.com/projects/ospnc/ gives me 502 Bad Gateway.

**Comment by ljharb** [comment]
ping @kaithar @LogIN

**Comment by kaithar** [comment]
Um, why did you ping me?

**Comment by ljharb** [comment]
You've got some commits, and sadly the website owner is nowhere to be found :-/ i was hoping you had some other way of contacting them.

**Comment by kaithar** [comment]
Nope, I only submitted a couple of patches.  Any reason you can't run it locally?

**Comment by ljharb** [comment]
I can't run it locally on a mobile device.

**Comment by kaithar** [comment]
Lol, fair point there I guess.  Let me see what I can do about setting it up on a public address.

**Comment by LogIN-** [comment]
Hey @ljharb,
thanks for reporting, it seems that VM where the site is hosted somehow crashed while ago :)
Now after pulling changes from master looks like page stopped working.. I will investigate this issues over the weekend and put project online!

**Comment by ljharb** [comment]
@LogIN- thank you!!! Much obliged :-) this is a very useful tool

**Comment by LogIN-** [comment]
@ljharb you can start using it.. But I still have some improvements to do on weekend....

**Comment by ljharb** [comment]
@LogIN- this appears to have happened again.

**Comment by LogIN-** [comment]
Site was transferred to a new server and a new DNS host.
It is working fine now and hopefully there will not be any downtime anymore in future since now process is now managed by pm2 module.


If you get some redirects or dont see the site please clear your Browser cache or try in another one.

**Comment by mlinksva** [comment]
502 Bad Gateway'd again.

**Comment by LogIN-** [comment]
@mlinksva  thanks, should be up now!
